num1=int(input('enter num1'))
num2=int(input('enter num2'))
print('add= ',num1+num2)
print('sub= ',num1-num2)
print('mul= ',num1*num2)
print('div= ',num1/num2)
print('mod= ',num1%num2)
print('exp= ',num1**num2)
print('floor div= ',num1//num2)

